# Build Pipeline for Setting up the Use Case 3 Infrastructure
# Triggered by a git push to the master branch
#
# Per default the pipeline runs on a self hosted agent on windows in the Default pool
# Use vmImage: 'windows-latest' to use a hosted agent (Free Tier requires upfront MS approval) 

trigger:
- master

pool:
  name: Default

#pool:
#  vmImage: 'windows-latest'

jobs:
- job: Chess-TrnReg
  displayName: 'Build Infra for Tournament Site'

  steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
    displayName: Install Terraform

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    displayName: 'Terraform : Init'
    inputs:
      provider: 'azurerm'
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform'
      backendServiceArm: SC4TF
      backendAzureRmResourceGroupName: 'tfstate'
      backendAzureRmStorageAccountName: 'tfstate1459'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: tf-webapp2.tfstate

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    displayName: 'Terraform : Plan'
    inputs:
      command: plan
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform'
      environmentServiceNameAzureRM: SC4TF

  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
    displayName: 'Terraform : Apply'
    inputs:
      command: apply
      workingDirectory: '$(System.DefaultWorkingDirectory)\terraform'
      environmentServiceNameAzureRM: SC4TF
      